# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
after_success:
- julia -e 'cd(Pkg.dir("AllanDeviations")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'